#
# This file is autogenerated during plugin quickstart and overwritten during
# plugin makedist. DO NOT CHANGE IT if you plan to use plugin makedist to update 
# the distribution.
#

from setuptools import setup, find_packages

kwargs = {'author': 'Katherine Dykes and George Scott',
 'author_email': 'systems.engineering@nrel.gov',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': 'NREL WISDEM modules for plant energy production and flow',
 'download_url': '',
 'include_package_data': True,
 'install_requires': ['openmdao.main'],
 'keywords': ['openmdao'],
 'license': 'Apache v. 2.0',
 #'maintainer': '',
 #'maintainer_email': '',
 'name': 'Plant_AEPSE',
 'package_data': {'Plant_AEPSE': []},
 'package_dir': {'': 'src'},
 'packages': ['Plant_AEPSE', 'Plant_AEPSE.test','Plant_AEPSE.NREL_CSM_AEP', 'Plant_AEPSE.Openwind.Enterprise'],
 'url': '',
 'version': '0.1',
 'zip_safe': False}


setup(**kwargs)

